name: Daily Check

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    
      - name: Get Version
        id: get_version
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH lede
          
          content=$(cat lede/include/kernel-6.1)
          regex="LINUX_KERNEL_HASH-(.*) = (.*)"
          if [[ $content =~ $regex ]]; then
            version=${BASH_REMATCH[1]}
            version=${version//[[:space:]]/}
            echo "Version: $version"
            echo "::set-output name=kernel_version:: $version"
          fi
          
          content=$(cat lede/package/lean/default-settings/files/zzz-default-settings)
          regex="DISTRIB_REVISION='(.*)'"
          if [[ $content =~ $regex ]]; then
            version=${BASH_REMATCH[1]}
            version=${version//[[:space:]]/}
            echo "Version: $version"
            echo "::set-output name=setting_version:: $version"
          fi
          
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Compare Files
        id: compare_files
        run: |
          content=$(cat kernel-6.1)
          regex="LINUX_KERNEL_HASH-(.*) = (.*)"
          if [[ $content =~ $regex ]]; then
            version=${BASH_REMATCH[1]}
            version=${version//[[:space:]]/}
            echo "Version: $version"
            echo "::set-output name=current_kernel_version:: $version"
          fi
          
          content=$(cat zzz-default-settings)
          regex="DISTRIB_REVISION='(.*)'"
          if [[ $content =~ $regex ]]; then
            version=${BASH_REMATCH[1]}
            version=${version//[[:space:]]/}
            echo "Version: $version"
            echo "::set-output name=current_setting_version:: $version"
          fi
          echo "----"
          echo steps.get_version.outputs.kernel_version;
          echo steps.get_version.outputs.setting_version;

      - name: Trigger Build Workflow
        if: steps.compare_files.outputs.current_kernel_version != steps.get_version.outputs.kernel_version || steps.compare_files.outputs.current_setting_version  != steps.get_version.outputs.setting_version
        run: |
          echo "文件不一致"
          rm -rf ${{ github.workspace }}/lede
          # 触发另一个工作流程
          # 使用以下代码触发另一个工作流程的运行
          # curl -X POST https://api.github.com/repos/uixsj/Openwrt-x86_64/actions/workflows/build-openwrt.yml/dispatches \
          #   -H "Authorization: Bearer ${{ secrets.RELEASE_TOKEN }}" \
          #   -H "Accept: application/vnd.github.v3+json"
