name: Daily Check Version

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  
on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    
      - name: Get Version
        id: get_version
        run: |
          git clone --depth 1 $REPO_URL -b $REPO_BRANCH lede
          
          content=$(cat lede/include/kernel-6.1)
          regex="LINUX_KERNEL_HASH-(.*) = (.*)"
          if [[ $content =~ $regex ]]; then
            version=${BASH_REMATCH[1]}
            version=${version//[[:space:]]/}
            echo "Version: $version"
            echo "::set-output name=kernel_version:: $version"
          fi
          
          content=$(cat lede/package/lean/default-settings/files/zzz-default-settings)
          regex="DISTRIB_REVISION='([^']*)'"
          if [[ $content =~ $regex ]]; then
            version=${BASH_REMATCH[1]}
            echo "Version: $version"
            echo "::set-output name=setting_version:: $version"
          fi
          
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Compare Files
        id: compare_files
        run: |
          k_version=$(cat VERSION | grep "kernel_version" | sed 's/kernel_version=\(.*\)/\1/')
          s_version=$(cat VERSION | grep "setting_version" | sed 's/setting_version=\(.*\)/\1/')
          echo "::set-output name=current_kernel_version:: $k_version"
          echo "::set-output name=current_setting_version:: $s_version"
          
          echo $k_version
          echo $s_version

      - name: Trigger Build Workflow
        if: steps.compare_files.outputs.current_kernel_version != steps.get_version.outputs.kernel_version && steps.compare_files.outputs.current_setting_version  != steps.get_version.outputs.setting_version
        run: |
          echo "new version."
          sed -i "s/kernel_version=.*/kernel_version=${{steps.get_version.outputs.kernel_version}}/" VERSION
          sed -i "s/setting_version=.*/setting_version=${{steps.get_version.outputs.setting_version}}/" VERSION
          rm -rf ${{ github.workspace }}/lede
          
          git config --local user.email "fake@mail.com"
          git config --local user.name "Jarvis"
          git add VERSION
          giterrorcheck=$(git commit -m "update VERSION file." -a)
          
          if echo "$giterrorcheck" | grep -q "nothing to commit"; then
            echo "Git commit error message：$giterrorcheck"
          else
            git push origin main
            echo "update VERSION file done."
          
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.RELEASE_TOKEN }}"\
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/uixsj/Openwrt-x86_64/actions/workflows/build-openwrt.yml/dispatches \
              -d '{"ref":"main"}'
          fi

